/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.teamlechuga.baloncestonbahugo;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.*;

/**
 *
 * @author GS2
 */
public class BaloncestoNBA extends javax.swing.JFrame {

    /**
     * Creates new form BaloncestoNBA
     */
    public BaloncestoNBA() {
        initComponents();
        setTitle("Estadísticas de Baloncesto");
        setSize(600, 400);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        iniciarBotones();
    }
    
    private void iniciarBotones() {
        Tiros2.addChangeListener(e -> {
            TirosTotales.setValue((int) Tiros2.getValue() + (int) Tiros3.getValue());
        });
        Tiros3.addChangeListener(e -> {
            TirosTotales.setValue((int) Tiros2.getValue() + (int) Tiros3.getValue());
        });

        Calcular.addActionListener(e -> {
            calcularYExportar(NombreJugador, Tiros2, Tiros3, TirosTotales);
        });
    }
    
    public static void escribirEnExcel(String nombreJugador, int tiros2, int tiros3, int tirosTotales) {
        File archivoExcel = new File("C:\\Users\\GS2\\Desktop\\EstadisticasBaloncesto.xlsx");
        Workbook libro = null;
        Sheet hoja;

        try {
            if (archivoExcel.exists()) {
                FileInputStream fis = new FileInputStream(archivoExcel);
                libro = new XSSFWorkbook(fis);
                hoja = libro.getSheetAt(0);
                fis.close();
            } else {
                libro = new XSSFWorkbook();
                hoja = libro.createSheet("Estadísticas de Jugadores");

                Row headerRow = hoja.createRow(0);
                headerRow.createCell(0).setCellValue("Nombre del Jugador");
                headerRow.createCell(1).setCellValue("Tiros de 2 Metidos");
                headerRow.createCell(2).setCellValue("Tiros de 3 Metidos");
                headerRow.createCell(3).setCellValue("Tiros Totales");
                headerRow.createCell(4).setCellValue("FG% (Porcentaje de tiros anotados)");
                headerRow.createCell(5).setCellValue("eFG% (Porcentaje efectivo)");
            }

            int siguiente = hoja.getLastRowNum() + 1;
            Row dataRow = hoja.createRow(siguiente);

            dataRow.createCell(0).setCellValue(nombreJugador);
            dataRow.createCell(1).setCellValue(tiros2);
            dataRow.createCell(2).setCellValue(tiros3);
            dataRow.createCell(3).setCellValue(tirosTotales);

            double fg = (tirosTotales > 0) ? ((double) (tiros2 + tiros3) / tirosTotales) * 100 : 0;
            dataRow.createCell(4).setCellValue(String.format("%.2f%%", fg));

            double efg = (tirosTotales > 0) ? ((tiros2 + (0.5 * tiros3)) / tirosTotales) * 100: 0;
            dataRow.createCell(5).setCellValue(String.format("%.2f%%", efg));

            for (int i = 0; i < 6; i++) {
                hoja.autoSizeColumn(i);
            }

            try (FileOutputStream fileOut = new FileOutputStream(archivoExcel)) {
                libro.write(fileOut);
                JOptionPane.showMessageDialog(null, "Datos exportados a Excel correctamente.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al escribir en Excel: " + e.getMessage());
        } finally {
            try {
                if (libro != null) {
                    libro.close();
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    public static void calcularYExportar(JTextField NombreJugador, JSpinner Tiros2, JSpinner Tiros3, JSpinner TirosTotales) {
        String nombreJugador = NombreJugador.getText();
        int tiros2 = (int) Tiros2.getValue();
        int tiros3 = (int) Tiros3.getValue();
        int tirosTotales = (int) TirosTotales.getValue();

        if (nombreJugador.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El nombre del jugador es obligatorio.");
            return;
        }

        escribirEnExcel(nombreJugador, tiros2, tiros3, tirosTotales);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        NombreJugadorTexto = new javax.swing.JLabel();
        Tiros2Texto = new javax.swing.JLabel();
        Tiros3Texto = new javax.swing.JLabel();
        TirosTotalesTexto = new javax.swing.JLabel();
        NombreJugador = new javax.swing.JTextField();
        Tiros2 = new javax.swing.JSpinner();
        Tiros3 = new javax.swing.JSpinner();
        TirosTotales = new javax.swing.JSpinner();
        Calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        NombreJugadorTexto.setText("Nombre de Jugador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(NombreJugadorTexto, gridBagConstraints);

        Tiros2Texto.setText("Tiros metidos de 2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(Tiros2Texto, gridBagConstraints);

        Tiros3Texto.setText("Tiros metidos de 3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(Tiros3Texto, gridBagConstraints);

        TirosTotalesTexto.setText("Tiros totales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(TirosTotalesTexto, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(NombreJugador, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(Tiros2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(Tiros3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(TirosTotales, gridBagConstraints);

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(Calcular, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaloncestoNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaloncestoNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaloncestoNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaloncestoNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaloncestoNBA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JLabel NombreJugadorTexto;
    private javax.swing.JSpinner Tiros2;
    private javax.swing.JLabel Tiros2Texto;
    private javax.swing.JSpinner Tiros3;
    private javax.swing.JLabel Tiros3Texto;
    private javax.swing.JSpinner TirosTotales;
    private javax.swing.JLabel TirosTotalesTexto;
    // End of variables declaration//GEN-END:variables
}
